{{ if .Values.infoblox.enabled }}
apiVersion: v1
data:
  INFOBLOX_GRID_HOST: {{ quote .Values.infoblox.gridHost }}
  INFOBLOX_WAPI_VERSION: {{ quote .Values.infoblox.wapiVersion }}
  INFOBLOX_WAPI_PORT: {{ quote .Values.infoblox.wapiPort }}
kind: ConfigMap
metadata:
  name: infoblox
{{ end }}
