name: Golang lint and test
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.svg'
      - '**.drawio'
      - '.spelling'
jobs:
  go-inspect:
    name: Inspect packages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # see: https://golangci-lint.run/usage/configuration/#config-file
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
      - name: go test
        run: go test ./...
