name: Terratest

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.svg'
      - '**.drawio'
      - '.spelling'

jobs:
  terratest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Create 1st k3s Cluster
        uses: AbsaOSS/k3d-action@v1.1.0
        with:
          cluster-name: "test-gslb1"
          use-default-registry: true
          args: >-
            -p "80:80@agent[0]"
            -p "443:443@agent[0]"
            -p "5053:53/udp@agent[0]"
            --agents 3
            --no-lb
            --network k3d-action-bridge-network
            --k3s-server-arg "--no-deploy=traefik,servicelb,metrics-server"

      - name: Create 2nd k3s Cluster
        uses: AbsaOSS/k3d-action@v1.1.0
        with:
          cluster-name: "test-gslb2"
          use-default-registry: true
          args: >-
            -p "81:80@agent[0]"
            -p "444:443@agent[0]"
            -p "5054:53/udp@agent[0]"
            --network k3d-action-bridge-network
            --agents 3
            --no-lb
            --k3s-server-arg "--no-deploy=traefik,servicelb,metrics-server"

      - name: K8GB deployment
        run: |
          GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.32.0
          make deploy-to-AbsaOSS-k3d-action

      - name: Terratest
        run: make terratest
